### ISSUE TITLE
Documentation incorrectly defines `subPath`

### ISSUE THREAD

**Issue by firasm** [pimsmath/syzygy-intro#4]
Hello creating an issue (and submitting a PR if it's welcome) to change something that is confusing in the teaching section. 

The described behaviour of the `subPath` argument described on the [teaching page](https://intro.syzygy.ca/teaching/) is different from what `nbgitpuller` says it is.

On this website, it says

> `subPath=path/to/file.ipynb` is an optional path within the repository to restrict the clone to a specific file or directory of interest.

On the [nbgitpuller](http://tljh.jupyter.org/en/latest/howto/content/nbgitpuller.html) repo, it says:

> `subPath` is the path of the directory / notebook inside the repo to launch after cloning. This parameter is optional, and defaults to opening the base directory of the linked Git repository.

I suggest updating the docs here to reflect what nbgitpuller says is happening.

---------------
There are also two additional arguments that may be of use from the `nbgitpuller` page :

`app` This parameter is optional and defaults to either the environment variable NBGITPULLER_APP’s value or notebook if it is undefined. The allowed values are lab and notebook, the value will determine in what application view you end up in.

`urlPath` will, if specified, override app and subPath and redirect blindly to the specified path.

**Comment by firasm** [comment]
And actually, it seems [according to this](https://jupyterhub.github.io/nbgitpuller/topic/url-options.html#deprecated-parameters) `subPath` is being deprecated in favour of urlPath.

**Comment by ianabc** [comment]
Thanks for this, I've merged PR #5
